version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

  redis:
    image: redis
    command: redis-server
    container_name: redis
    ports:
      - "6379:6379"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  chat-system:
    build:
      dockerfile: ./Dockerfile
      context: ./chat_system
    command: sh ./start.sh
    ports:
      - "3200:3200"
    restart: always
    depends_on:
      - elasticsearch
      - mysql
    links:
      - mysql
      - redis
    environment:
      REDIS_URL_CACHING: redis://redis:6379/0
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_PORT: 3306
      DB_HOST: mysql

volumes:
  redis:
  db_data: